# Generated by Django 2.2.5 on 2019-09-30 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miktel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telefon',
            name='imei',
            field=models.CharField(max_length=15, verbose_name='imei'),
        ),
    ]
