# Generated by Django 2.2.5 on 2019-09-19 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('miktel', '0002_auto_20190919_0831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telefon',
            name='faktura',
        ),
        migrations.AddField(
            model_name='telefon',
            name='faktura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='miktel.FakturaZakupu'),
        ),
    ]
