# Generated by Django 2.2.6 on 2019-10-28 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('miktel', '0002_auto_20190930_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='telefon',
            name='data_sprzed',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='telefon',
            name='data_wprow',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='telefon',
            name='document',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Nr dokumentu'),
        ),
        migrations.AddField(
            model_name='telefon',
            name='info',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Informacje'),
        ),
        migrations.AddField(
            model_name='telefon',
            name='magazyn_aktualny',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Sklep_aktualny', to='miktel.Sklep', verbose_name='Aktualnie dostępny w:'),
        ),
    ]
