# Generated by Django 2.2.6 on 2019-10-28 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miktel', '0003_auto_20191028_0628'),
    ]

    operations = [
        migrations.AddField(
            model_name='telefon',
            name='zawieszony',
            field=models.BooleanField(default=True),
        ),
    ]
