# Generated by Django 2.2.6 on 2019-10-28 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miktel', '0004_telefon_zawieszony'),
    ]

    operations = [
        migrations.RenameField(
            model_name='telefon',
            old_name='document',
            new_name='nr_doc',
        ),
    ]
