# Generated by Django 2.2.5 on 2019-09-19 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('miktel', '0004_auto_20190919_0838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fakturazakupu',
            name='telefon',
        ),
        migrations.AddField(
            model_name='fakturazakupu',
            name='telefon',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='miktel.Telefon'),
        ),
    ]
