# Generated by Django 2.2.6 on 2019-10-28 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miktel', '0005_auto_20191028_0642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telefon',
            name='zawieszony',
            field=models.BooleanField(default=False),
        ),
    ]
