# Generated by Django 2.2.5 on 2019-09-19 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miktel', '0005_auto_20190919_1846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fakturazakupu',
            name='telefon',
        ),
        migrations.AddField(
            model_name='fakturazakupu',
            name='telefon',
            field=models.ManyToManyField(to='miktel.Telefon'),
        ),
    ]
