# Generated by Django 2.2.6 on 2019-10-28 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miktel', '0007_telefon_data_zmiany'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telefon',
            name='data_zmiany',
        ),
    ]
