# Generated by Django 2.2.6 on 2019-10-28 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miktel', '0008_remove_telefon_data_zmiany'),
    ]

    operations = [
        migrations.AddField(
            model_name='telefon',
            name='data_zmiany',
            field=models.DateField(blank=True, null=True),
        ),
    ]
