# Generated by Django 2.2.5 on 2019-09-21 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miktel', '0008_auto_20190921_0627'),
    ]

    operations = [
        migrations.RenameField(
            model_name='telefon',
            old_name='prcownik_out',
            new_name='pracownik_out',
        ),
    ]
