# Generated by Django 2.2.5 on 2019-09-21 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('miktel', '0009_auto_20190921_0636'),
    ]

    operations = [
        migrations.AddField(
            model_name='telefon',
            name='sklep_sprzed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sklep_sprzadzy', to='miktel.Sklep'),
        ),
    ]
