# Generated by Django 2.2.6 on 2019-11-04 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miktel', '0009_telefon_data_zmiany'),
    ]

    operations = [
        migrations.AddField(
            model_name='sklep',
            name='serwis_zew',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='telefon',
            name='data_zmiany',
            field=models.DateField(blank=True, null=True, verbose_name='Data zmiany (YYYY-MM-DD)'),
        ),
    ]
