# Generated by Django 2.2.6 on 2019-11-05 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miktel', '0010_auto_20191104_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dodajserwis',
            name='numer_telefonu',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='telefon',
            name='cena_sprzed',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
