# Generated by Django 2.2.5 on 2019-09-21 05:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('miktel', '0011_remove_telefon_pracownik_out'),
    ]

    operations = [
        migrations.AddField(
            model_name='telefon',
            name='pracownik_add',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='przyjmujacy', to=settings.AUTH_USER_MODEL),
        ),
    ]
