# Generated by Django 2.2.6 on 2019-11-26 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miktel', '0011_auto_20191105_0807'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='telefon',
            options={'ordering': ('-id', 'marka', 'nazwa')},
        ),
        migrations.AlterField(
            model_name='dodajserwis',
            name='imei',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
