# Generated by Django 2.2.5 on 2019-09-21 05:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('miktel', '0013_remove_telefon_pracownik_add'),
    ]

    operations = [
        migrations.AddField(
            model_name='telefon',
            name='pracownik_sprzed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sprzdawal', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='telefon',
            name='pracownik_zak',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='przyjmowal', to=settings.AUTH_USER_MODEL),
        ),
    ]
