# Generated by Django 2.2.5 on 2019-09-22 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miktel', '0014_auto_20190921_0742'),
    ]

    operations = [
        migrations.AddField(
            model_name='premiajob',
            name='check_id',
            field=models.IntegerField(default=1),
        ),
    ]
