# Generated by Django 2.2.5 on 2019-09-22 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miktel', '0015_premiajob_check_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premiajob',
            name='check_id',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
