# Generated by Django 2.2.5 on 2019-09-22 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miktel', '0016_auto_20190922_0627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premiajob',
            name='check_id',
            field=models.IntegerField(default=1),
        ),
    ]
