# Generated by Django 2.2.5 on 2019-09-22 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miktel', '0017_auto_20190922_0639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premiajob',
            name='check_id',
            field=models.IntegerField(),
        ),
    ]
