# Generated by Django 2.2.5 on 2019-09-22 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('miktel', '0019_auto_20190922_0646'),
    ]

    operations = [
        migrations.CreateModel(
            name='Typ',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nazwa', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='foto',
            name='used',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nazwa', models.CharField(max_length=64)),
                ('date_add', models.DateField(auto_now_add=True)),
                ('cena_zak', models.IntegerField()),
                ('ilosc', models.IntegerField()),
                ('opis', models.CharField(blank=True, max_length=128, null=True)),
                ('dostepny', models.BooleanField(default=True)),
                ('foto', models.ManyToManyField(blank=True, to='miktel.Foto', verbose_name='Foto_produktu')),
                ('marka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miktel.Marka')),
                ('sklep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miktel.Sklep', verbose_name='Magazyn')),
                ('typ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miktel.Typ')),
            ],
        ),
    ]
