# Generated by Django 2.2.5 on 2019-09-22 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miktel', '0020_auto_20190922_0809'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Czesc',
        ),
    ]
