# Generated by Django 2.2.5 on 2019-09-22 06:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('miktel', '0021_auto_20190922_0810'),
    ]

    operations = [
        migrations.AddField(
            model_name='czesc',
            name='pracownik',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Wprowadził'),
        ),
    ]
