# Generated by Django 2.2.5 on 2019-09-22 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miktel', '0022_czesc_pracownik'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='czesc',
            options={'ordering': ('marka', 'typ', 'nazwa')},
        ),
        migrations.AlterModelOptions(
            name='typ',
            options={'ordering': ('nazwa',)},
        ),
        migrations.AddField(
            model_name='czesc',
            name='cena_sprzed',
            field=models.IntegerField(default=0),
        ),
    ]
