# Generated by Django 2.2.5 on 2019-09-22 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miktel', '0024_czesc_stan'),
    ]

    operations = [
        migrations.AddField(
            model_name='czesc',
            name='kolor',
            field=models.IntegerField(choices=[(0, 'Czarny'), (1, 'Biały'), (2, 'Złoty'), (3, 'Niebieski'), (4, 'Inny')], default=0, verbose_name='Kolor czesci'),
        ),
        migrations.AlterField(
            model_name='czesc',
            name='stan',
            field=models.IntegerField(choices=[(0, 'Nowy'), (1, 'Używany'), (2, 'Zamiennik'), (3, 'Z demontażu')], default=0, verbose_name='Stan czesci'),
        ),
    ]
