# Generated by Django 2.2.5 on 2019-09-23 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('miktel', '0027_auto_20190922_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='dodajserwis',
            name='marka',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='miktel.Marka', verbose_name='Wybierz marke'),
        ),
    ]
