# Generated by Django 2.2.5 on 2019-09-24 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miktel', '0028_dodajserwis_marka'),
    ]

    operations = [
        migrations.AlterField(
            model_name='czesc',
            name='cena_sprzed',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
