# Generated by Django 2.2.5 on 2019-09-24 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miktel', '0029_auto_20190924_0743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premiajob',
            name='check',
            field=models.IntegerField(default=0),
        ),
    ]
