# Generated by Django 2.2.5 on 2019-09-24 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('miktel', '0032_usluga_akcesoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telefon',
            name='kategoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miktel.Kategoria'),
        ),
        migrations.AlterField(
            model_name='telefon',
            name='marka',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miktel.Marka'),
        ),
    ]
