# Generated by Django 2.2.5 on 2019-09-24 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miktel', '0033_auto_20190924_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telefon',
            name='stan',
            field=models.IntegerField(choices=[(0, 'Nowy'), (1, 'Używany'), (2, 'Bez pudełka')], verbose_name='Stan telefon'),
        ),
    ]
