# Generated by Django 3.0.4 on 2020-04-03 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miktel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='site_id',
            field=models.IntegerField(blank=True, choices=[(1, 'Home'), (2, 'GSM'), (3, 'Grawerowanie'), (5, 'Klucze'), (4, 'Pieczątki')], null=True, verbose_name='Strona'),
        ),
    ]
