# Generated by Django 3.0.4 on 2020-04-03 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miktel', '0002_auto_20200403_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='adres',
            name='google_maps',
            field=models.TextField(blank=True, null=True, verbose_name='link do google maps'),
        ),
        migrations.AddField(
            model_name='adres',
            name='latitude',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='lititude'),
        ),
        migrations.AddField(
            model_name='adres',
            name='longitude',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='longitude'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='site_id',
            field=models.IntegerField(blank=True, choices=[(1, 'Home'), (4, 'Pieczątki'), (5, 'Klucze'), (3, 'Grawerowanie'), (2, 'GSM')], null=True, verbose_name='Strona'),
        ),
    ]
