# Generated by Django 3.0.3 on 2021-08-17 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miktel', '0003_auto_20201106_0716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='site_id',
            field=models.IntegerField(blank=True, choices=[(2, 'GSM'), (3, 'Grawerowanie'), (4, 'Pieczątki'), (5, 'Klucze'), (1, 'Home')], null=True, verbose_name='Strona'),
        ),
    ]
