# Generated by Django 3.0.4 on 2020-04-09 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miktel', '0003_auto_20200403_0953'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='czesc',
            options={'ordering': ('marka', 'nazwa'), 'verbose_name_plural': 'Czesci_gsm'},
        ),
        migrations.AddField(
            model_name='czesc',
            name='cena_promo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='czesc',
            name='in_promo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='telefon',
            name='cena_promo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='telefon',
            name='in_promo',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='articles',
            name='site_id',
            field=models.IntegerField(blank=True, choices=[(1, 'Home'), (4, 'Pieczątki'), (2, 'GSM'), (5, 'Klucze'), (3, 'Grawerowanie')], null=True, verbose_name='Strona'),
        ),
    ]
