# Generated by Django 3.0.4 on 2020-04-09 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miktel', '0004_auto_20200409_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='site_id',
            field=models.IntegerField(blank=True, choices=[(2, 'GSM'), (4, 'Pieczątki'), (5, 'Klucze'), (3, 'Grawerowanie'), (1, 'Home')], null=True, verbose_name='Strona'),
        ),
        migrations.AlterField(
            model_name='telefon',
            name='cena_promo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
