# Generated by Django 3.0.3 on 2020-03-16 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miktel', '0004_auto_20200315_1915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='name_slug',
        ),
    ]
