# Generated by Django 3.0.4 on 2020-04-18 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miktel', '0005_auto_20200409_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='is_sale',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='products',
            name='sale',
            field=models.IntegerField(choices=[(0, 'Nie'), (1, 'Sale -10%'), (2, 'Sale -20%'), (3, 'Sale -30%'), (4, 'Sale -40%'), (5, 'Sale -50%'), (6, 'All 5 zł'), (7, 'All 10 zł'), (8, 'All 15 zł'), (9, 'All 20 zł')], default=0, verbose_name='Wyprzedaż'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='site_id',
            field=models.IntegerField(blank=True, choices=[(1, 'Home'), (2, 'GSM'), (5, 'Klucze'), (3, 'Grawerowanie'), (4, 'Pieczątki')], null=True, verbose_name='Strona'),
        ),
    ]
