# Generated by Django 3.0.4 on 2020-05-01 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('miktel', '0006_auto_20200418_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotoproduct',
            name='factory_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='miktel.Factory'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='site_id',
            field=models.IntegerField(blank=True, choices=[(2, 'GSM'), (4, 'Pieczątki'), (1, 'Home'), (3, 'Grawerowanie'), (5, 'Klucze')], null=True, verbose_name='Strona'),
        ),
    ]
