# Generated by Django 3.0.4 on 2020-05-01 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miktel', '0007_auto_20200501_0900'),
    ]

    operations = [
        migrations.RenameField(
            model_name='factory',
            old_name='name_slug',
            new_name='slug',
        ),
        migrations.AlterField(
            model_name='articles',
            name='site_id',
            field=models.IntegerField(blank=True, choices=[(5, 'Klucze'), (2, 'GSM'), (1, 'Home'), (3, 'Grawerowanie'), (4, 'Pieczątki')], null=True, verbose_name='Strona'),
        ),
    ]
