# Generated by Django 3.0.4 on 2020-05-08 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miktel', '0008_auto_20200501_0912'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marka',
            options={'ordering': ('nazwa',), 'verbose_name_plural': 'Marka'},
        ),
        migrations.AddField(
            model_name='marka',
            name='gsm',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='marka',
            name='keys',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='marka',
            name='slug',
            field=models.SlugField(blank=True, max_length=128, null=True, verbose_name='Nazwa slug'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='site_id',
            field=models.IntegerField(blank=True, choices=[(1, 'Home'), (3, 'Grawerowanie'), (5, 'Klucze'), (4, 'Pieczątki'), (2, 'GSM')], null=True, verbose_name='Strona'),
        ),
    ]
