# Generated by Django 3.0.4 on 2020-06-10 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miktel', '0009_auto_20200508_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='site_id',
            field=models.IntegerField(blank=True, choices=[(5, 'Klucze'), (2, 'GSM'), (3, 'Grawerowanie'), (4, 'Pieczątki'), (1, 'Home')], null=True, verbose_name='Strona'),
        ),
        migrations.AlterField(
            model_name='workschedule',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AddIndex(
            model_name='czesc',
            index=models.Index(fields=['marka', 'typ', 'nazwa', 'sklep'], name='miktel_czes_marka_i_1994d0_idx'),
        ),
        migrations.AddIndex(
            model_name='dodajserwis',
            index=models.Index(fields=['sklep', 'status'], name='miktel_doda_sklep_i_f1ae90_idx'),
        ),
        migrations.AddIndex(
            model_name='myuser',
            index=models.Index(fields=['sklep_dzisiaj'], name='miktel_myus_sklep_d_0ba62e_idx'),
        ),
        migrations.AddIndex(
            model_name='premiajob',
            index=models.Index(fields=['pracownik', 'sklep'], name='miktel_prem_pracown_70e8d3_idx'),
        ),
        migrations.AddIndex(
            model_name='products',
            index=models.Index(fields=['category_id', 'name', 'shop_id'], name='miktel_prod_categor_a7298d_idx'),
        ),
        migrations.AddIndex(
            model_name='sklep',
            index=models.Index(fields=['adres'], name='miktel_skle_adres_i_e8b51c_idx'),
        ),
        migrations.AddIndex(
            model_name='telefon',
            index=models.Index(fields=['sklep', 'dostepny', 'marka', 'nazwa'], name='miktel_tele_sklep_i_c42e46_idx'),
        ),
        migrations.AddIndex(
            model_name='umowakomisowanew',
            index=models.Index(fields=['phones', 'sprzedana'], name='miktel_umow_phones__c1273b_idx'),
        ),
    ]
