# Generated by Django 3.0.4 on 2020-11-06 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miktel', '0010_auto_20200610_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='sklep',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='articles',
            name='site_id',
            field=models.IntegerField(blank=True, choices=[(2, 'GSM'), (5, 'Klucze'), (1, 'Home'), (3, 'Grawerowanie'), (4, 'Pieczątki')], null=True, verbose_name='Strona'),
        ),
    ]
