from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from miktel.views import *
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', MainView.as_view(), name="widok_klienta"),

    #SEKCJA TELEFONY UMOWY I FAKTURY
    path('dodaj_telefon/', TelefonCreateView.as_view(), name="dodaj_telefon"),
    path('telefony_magazyn/',
         TelefonyMagazynView.as_view(),
         name="telefony_magazyn"),
    path('telefony_dostepne_magazyn/<int:pk>',
         TelefonyMagazynFilterView.as_view(),
         name="telefony_magazyn_filter"),
     path('telefony_sprzedane_magazyn/<int:pk>',
         TelefonySprzedaneMagazynFilterView.as_view(),
         name="telefony_sprzedane_magazyn_filter"),
    path('add_info/<int:pk>',
         TelefonyMagazynInfoView.as_view(),
         name="telefony_info"),
    path('change_mag/<int:pk>',
         TelefonyMagazynChangeView.as_view(),
         name="change_mag"),
    path('sell_phones/<int:pk>', SellPhonesView.as_view(), name="sell_phone"),
    path('telefony_sprzedane/',
         TelefonySprzedaneView.as_view(),
         name="telefony_sprzedane"),
    path('telefony_zawieszone/',
         TelefonyZawieszoneView.as_view(),
         name="telefony_zawieszone"),
    path('reklamacja/<int:pk>',
         TelefonyReklamacjaView.as_view(),
         name="telefony_reklamacja"),
    path('wystaw_telefon/<int:pk>',
         WystawTelefonView.as_view(),
         name='wystaw_telefon'),
    path('szczegoly_telefonu/<int:pk>',
         SzczegolyTelefonuView.as_view(),
         name='szczegoly_telefonu'),
    path('umowa_komisowa/', UmowaKomisowaView.as_view(),
         name="umowa_komisowa"),
    path('lista_umow/', ListaUmowView.as_view(), name="lista_umow"),
    path('edycja_umowy/<int:pk>',
         EdycjaUmowyView.as_view(),
         name="edycja_umowy"),
    path('checking_document/',
         CheckingDocumentView.as_view(),
         name="checking_document/"),
    path('umowa_imei/<int:pk>', UmowaIdView.as_view(), name="umowa_imei"),
    path('faktura_imei/<int:pk>', FakturaIdView.as_view(),
         name="faktura_imei"),
    path('faktura_zakupu/', FakturaZakupuView.as_view(),
         name="faktura_zakupu"),
    path('checking_invoice/',
         CheckingInvoiceView.as_view(),
         name="checking_invoice"),
    path('lista_faktur/', ListaFakturView.as_view(), name="lista_faktur"),
    path('delete_invoice/<int:pk>', DeleteFakturaZakupuView .as_view(), name="delete_invoice"),
    path('edycja_faktury/<int:pk>',
         EdycjaFakturyView.as_view(),
         name="edycja_faktury"),
    path('wystaw_telefon/<int:pk>',
         WystawTelefonView.as_view(),
         name='wystaw_telefon'),

    #SEKCJA SERIWS I CZESCI
    path('dodaj_serwis/', DodajSerwisView.as_view(), name="dodaj_serwis"),
    path('szczegoly_serwisu/<int:pk>',
         SzczegolySerwisuView.as_view(),
         name='szczegoly_serwisu'),
    path('gotowy_do_odbioru/<int:pk>',
         GotowySerwisView.as_view(),
         name='gotowy_serwis'),
    path('wykonaj_serwis_z_czesciami/<int:pk>',
         GetServiceForItems.as_view(),
         name='wykonaj_serwis_z_czesciami'),
    path('save_service/<int:pk>',
         ServiceReadyView.as_view(),
         name='save_service'),
    path('wydaj_serwis/<int:pk>',
         WydajSerwisView.as_view(),
         name='wydaj_serwis'),
    path('wydaj_serwis_czesci/',
         WydajSerwisCzesciView.as_view(),
         name='wydaj_serwis_czesci'),
    path('wydaj_serwis_czesci2/',
         WydajSerwisCzesci2View.as_view(),
         name='wydaj_serwis_czesci2'),
    path('archiwum_serwisow/',
         ArchiwumSerwisView.as_view(),
         name='archiwum_serwisow'),
    path('reklamacja_serwis/<int:pk>',
         ReklamacjaSerwisView.as_view(),
         name='reklamacja_serwis'),
    path('lista_serwisow/',
         ListaSerwisowMagazynView.as_view(),
         name="lista_serwisow"),
     path('lista_serwisow/<int:pk>',
         ListaSerwisowFilterMagazynView.as_view(),
         name="lista_serwisow_filter"),
    path('lista_serwisow_gotowych/',
         ListaSerwisowGotowychMagazynView.as_view(),
         name="lista_serwisow_gotowych"),
     path('lista_serwisow_gotowych_filter/<int:pk>',
         ListaSerwisowGotowychFilterMagazynView.as_view(),
         name="lista_serwisow_gotowych_filter"),

    #SEKCJA PDF
    path('generuj_pdf/<int:pk>', GenerujPdfView.as_view(), name='pdf_umowa'),
    path('serwis_pdf/<int:pk>',
         DodajPDFSerwisView.as_view(),
         name="serwis_pdf"),

    #SEKCJA CZĘŚCI
    path('dodaj_czesc/', CzesciCreateView.as_view(), name='dodaj_czesc'),
    path('lista_czesci/', ListaCzesciView.as_view(), name='lista_czesci'),
    path('szczegoly_czesci/<int:pk>',
         SzczegolyCzesciView.as_view(),
         name="szczegoly_czesci"),
    path('uzyj_czesci/', UzyjCzesciWieleView.as_view(), name="uzyj_czesci"),
    path('uzyj_czesci_serwis/',
         UzyjCzesciSerwisView.as_view(),
         name="uzyj_czesci_serwis"),
    path('usun_wiecej_czesci/<int:pk>',
         RemoveMoreItemsView.as_view(),
         name="usun_wiecej_czesci"),
    path('dodaj_wiecej_czesci/<int:pk>',
         AddMoreItemsView.as_view(),
         name="dodaj_wiecej_czesci"),
    path('dodaj_podobna_czesc/<int:pk>',
         AddMoreItemsSimiliarView.as_view(),
         name="dodaj_podobna_czesc"),

    #SEKCJA ADMINISTRACJI
    path('profil/<int:pk>', ProfilView.as_view(), name="profil"),
    path('lista_uzytkownikow/',
         ListaMyUserView.as_view(),
         name="lista_uzytkownikow"),
    path('dodaj_uzytkownika/',
         DodajPracownikaView.as_view(),
         name="dodaj_uzytkownika"),
    path('edycja_uzytkownika/<int:pk>',
         EdycjaMyUserView.as_view(),
         name="edycja_uzytkownika"),
    path('lista_sklepow/', ListaSklepowView.as_view(), name="lista_sklepow"),
    path('edycja_sklepu/<int:pk>',
         EdycjaSklepuView.as_view(),
         name="edycja_sklepu"),
    path('dodaj_foto/', DodajFotoView.as_view(), name="dodaj_foto"),
    path('ustaw_foto/<int:pk>',
         UstawFotoProfilView.as_view(),
         name="ustaw_foto"),
    #     path('ustaw_page_records/',
    #          PageRecordsView.as_view(),
    #          name="ustaw_page_records"),
    path('ustaw_haslo/<int:pk>', UstawHasloView.as_view(), name="ustaw_haslo"),
    path('dodaj_sklep/', AddShopView.as_view(), name="dodaj_sklep"),
    path('dodaj_marke/', AddCompanyView.as_view(), name="dodaj_marke"),
    path('dodaj_typ/', AddTypeItemView.as_view(), name="dodaj_typ"),
    path('dodaj_adres/', AddAdresView.as_view(), name="dodaj_adres"),
    path('dodaj_hurtownie/',
         AddHurtowniaView.as_view(),
         name="dodaj_hurtownie"),
    path('dodaj_kategorie/', AddCategoryView.as_view(),
         name="dodaj_kategorie"),
    path('dodaj_inne/', DodajInnePraceView.as_view(), name='dodaj_inne_prace'),

     path('delete_document/<int:pk>',
              DeleteDocumentView.as_view(),
             name="delete_document"),
    path('lista_uslug/', ListaUslugView.as_view(), name="lista_uslug"),
    path('dodaj_usluge/', DodajUslugaView.as_view(), name="dodaj_usluge"),
    path('edycja_uslugi/<int:pk>',
         EdycjaUslugiView.as_view(),
         name="edycja_uslugi"),
    path('usun_usluge/<int:pk>',
         DeleteUslugaView.as_view(),
         name="usun_usluge"),

    #SECKJA PREMIOWANIE
    path('akcesoria_gsm_miesiąc/',
         DodajAkcesoriaView.as_view(),
         name="akcesoria_gsm_miesiąc/"),
    path('dashboard_sklepow/',
         DashboardView.as_view(),
         name="dashboard_sklepow"),
    path('dodaj_premiaJob/',
         DodajPremiaJobView.as_view(),
         name="dodaj_premiaJob"),
    path('twoje_premie/', TwojePremieJobView.as_view(),
         name="twoje_premieJob"),
    path('edycja_premiaJob/<int:pk>',
         EdycjaPremiaJobView.as_view(),
         name="edycja_premiaJob"),
    path('szczegoly_serwisow_serwisanta/<int:pk>/<int:miesiac>/<int:rok>/',
         SzczegolySerwisySerwisantaView.as_view(),
         name='szczegoly_serwisow_serwisanta'),
    path('login/', UserLoginView.as_view(), name="login"),
    path('logout/', User_Logout),
] + static(settings.STATIC_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:  # new
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
